[[participants]]
name = "Ioana-Steliana Barbu"
school = "Colegiul Național „Spiru Haret” Tulcea"
award = "Medalie de aur"
photo = "/blog/iol-2025/Aur-Barbu-Ioana.jpg"

[[participants]]
name = "Mihaela Anghel"
school = "Liceul Teoretic „Alexandru Ghica” Alexandria"
award = "Medalie de bronz"
photo = "/blog/iol-2025/Bronz-Anghel-Mihaela.jpg"

[[participants]]
name = "Andrei Dragu"
school = "Colegiul Național de Informatică „Tudor Vianu” București"
award = "Medalie de bronz"
photo = "/blog/iol-2025/Bronz-Dragu-Andrei.jpg"

[[participants]]
name = "Luiza-Teodora Mihai"
school = "Colegiul Național Iași"
award = "Medalie de bronz"
photo = "/blog/iol-2025/Bronz-Mihai-Luiza.jpg"

[[participants]]
name = "Valeriia Pishchymukha"
school = "Colegiul Național „George Coșbuc” Cluj-Napoca"
award = "Medalie de bronz"
photo = "/blog/iol-2025/Bronz-Pishchymukha-Valeriia.jpg"

[[participants]]
name = "Ioana Stănoiu"
school = "Liceul Teoretic Internațional de Informatică București"
award = "Medalie de bronz"
photo = "/blog/iol-2025/Bronz-Stanoiu-Ioana.jpg"

[[participants]]
name = "Alin-Cristian Chindea"
school = "Colegiul Național „Ion Maiorescu” Giurgiu"
award = "Mențiune onorabilă"
photo = "/blog/iol-2025/Mentiune-Chindea-Alin.jpg"

[[participants]]
name = "Ana-Teodora Grigorie"
school = "Colegiul Național „Carol I” Craiova"
award = "Mențiune onorabilă"
photo = "/blog/iol-2025/Mentiune-Grigore-Ana.jpg"